using System.Collections;
using System.Collections.Generic;
using UnityEngine;
public class BadWordFilter : MonoBehaviour {


    
   public List<string>
        AR_Arabic,
        ID_Indonesia,
        MS_Malaysia,
        BS_Bosnian,
        PT_BrazilianPortuguese,
        BG_Bulgarian,
        CA_Catalan,
        ZH_ChineseSimplified,
        ZH_ChineseTraditional,
        HR_Croatian,
        CS_Czech,
        DA_DK,
        NL_Dutch,
        EN_English,
        EnGb_EnglishUK,
        ET_Estonian,
        FI_Finnish = new List<string>();




    private void Start()
    {
        enWords();
        DaWords();
        Debug.Log(EN_English.Count + " English bad words");
        Debug.Log(DA_DK.Count + " Danish Bad Words");
    }


    //English
    public void enWords() {


        EN_English.Add("4r5e");
        EN_English.Add("5h1t");
        EN_English.Add("5hit");
        EN_English.Add("a55");
        EN_English.Add("anal");
        EN_English.Add("anus");
        EN_English.Add("ar5e");
        EN_English.Add("arrse");
        EN_English.Add("arse");
        EN_English.Add("ass");
        EN_English.Add("ass-fucker");
        EN_English.Add("fucker");
        EN_English.Add("asses");
        EN_English.Add("assfucker");
        EN_English.Add("assfukka");
        EN_English.Add("asshole");
        EN_English.Add("assholes");
        EN_English.Add("asswhole");
        EN_English.Add("a_s_s");
        EN_English.Add("b!tch");
        EN_English.Add("b00bs");
        EN_English.Add("b17ch");
        EN_English.Add("b1tch");
        EN_English.Add("ballbag");
        EN_English.Add("balls");
        EN_English.Add("ballsack");
        EN_English.Add("bastard");
        EN_English.Add("beastial");
        EN_English.Add("beastiality");
        EN_English.Add("bellend");
        EN_English.Add("bestial");
        EN_English.Add("bestiality");
        EN_English.Add("bi + ch");
        EN_English.Add("biatch");
        EN_English.Add("bitch");
        EN_English.Add("bitcher");
        EN_English.Add("bitchers");
        EN_English.Add("bitches");
        EN_English.Add("bitchin");
        EN_English.Add("bitching");
        EN_English.Add("bloody");
        EN_English.Add("blow job");
        EN_English.Add("blowjob");
        EN_English.Add("blowjobs");
        EN_English.Add("boiolas");
        EN_English.Add("bollock");
        EN_English.Add("bollok");
        EN_English.Add("boner");
        EN_English.Add("boob");
        EN_English.Add("boobs");
        EN_English.Add("booobs");
        EN_English.Add("boooobs");
        EN_English.Add("booooobs");
        EN_English.Add("booooooobs");
        EN_English.Add("buceta");
        EN_English.Add("bugger");
        EN_English.Add("bum");
        EN_English.Add("bunny fucker");
        EN_English.Add("2butt");
        EN_English.Add("butthole");
        EN_English.Add("buttmuch");
        EN_English.Add("buttplug");
        EN_English.Add("c0ck");
        EN_English.Add("c0cksucker");
        EN_English.Add("carpet muncher");
        EN_English.Add("cawk");
        EN_English.Add("chink");
        EN_English.Add("cipa");
        EN_English.Add("cl1t");
        EN_English.Add("clit");
        EN_English.Add("clitoris");
        EN_English.Add("clits");
        EN_English.Add("cnut");
        EN_English.Add("cock");
        EN_English.Add("cock - sucker");
        EN_English.Add("cockface");
        EN_English.Add("cockhead");
        EN_English.Add("cockmunch");
        EN_English.Add("cockmuncher");
        EN_English.Add("cocks");
        EN_English.Add("cocksuck");
        EN_English.Add("cocksucked");
        EN_English.Add("cocksucker");
        EN_English.Add("cocksucking");
        EN_English.Add("cocksucks");
        EN_English.Add("cocksuka");
        EN_English.Add("cocksukka");
        EN_English.Add("cok");
        EN_English.Add("cokmuncher");
        EN_English.Add("coksucka");
        EN_English.Add("coon");
        EN_English.Add("cox");
        EN_English.Add("crap");
        EN_English.Add("cum");
        EN_English.Add("cummer");
        EN_English.Add("cumming");
        EN_English.Add("cums");
        EN_English.Add("cumshot");
        EN_English.Add("cunilingus");
        EN_English.Add("cunillingus");
        EN_English.Add("cunnilingus");
        EN_English.Add("cunt");
        EN_English.Add("cuntlick");
        EN_English.Add("cuntlicker");
        EN_English.Add("cuntlicking");
        EN_English.Add("cunts");
        EN_English.Add("cyalis");
        EN_English.Add("cyberfuc");
        EN_English.Add("cyberfuck");
        EN_English.Add("cyberfucked");
        EN_English.Add("cyberfucker");
        EN_English.Add("cyberfuckers");
        EN_English.Add("cyberfucking");
        EN_English.Add("d1ck");
        EN_English.Add("damn");
        EN_English.Add("dick");
        EN_English.Add("dickhead");
        EN_English.Add("dildo");
        EN_English.Add("dildos");
        EN_English.Add("dink");
        EN_English.Add("dinks");
        EN_English.Add("dirsa");
        EN_English.Add("dlck");
        EN_English.Add("dog - fucker");
        EN_English.Add("doggin");
        EN_English.Add("dogging");
        EN_English.Add("donkeyribber");
        EN_English.Add("doosh");
        EN_English.Add("duche");
        EN_English.Add("dyke");
        EN_English.Add("ejaculate");
        EN_English.Add("ejaculated");
        EN_English.Add("ejaculates");
        EN_English.Add("ejaculating");
        EN_English.Add("ejaculatings");
        EN_English.Add("ejaculation");
        EN_English.Add("ejakulate");
        EN_English.Add("f u c k");
        EN_English.Add("f u c k e r");
        EN_English.Add("f4nny");
        EN_English.Add("fag");
        EN_English.Add("fagging");
        EN_English.Add("faggitt");
        EN_English.Add("faggot");
        EN_English.Add("faggs");
        EN_English.Add("fagot");
        EN_English.Add("fagots");
        EN_English.Add("fags");
        EN_English.Add("fanny");
        EN_English.Add("fannyflaps");
        EN_English.Add("fannyfucker");
        EN_English.Add("fanyy");
        EN_English.Add("fatass");
        EN_English.Add("fcuk");
        EN_English.Add("fcuker");
        EN_English.Add("fcuking");
        EN_English.Add("feck");
        EN_English.Add("fecker");
        EN_English.Add("felching");
        EN_English.Add("fellate");
        EN_English.Add("fellatio");
        EN_English.Add("fingerfuck");
        EN_English.Add("fingerfucked");
        EN_English.Add("fingerfucker");
        EN_English.Add("fingerfuckers");
        EN_English.Add("fingerfucking");
        EN_English.Add("fingerfucks");
        EN_English.Add("fistfuck");
        EN_English.Add("fistfucked");
        EN_English.Add("fistfucker");
        EN_English.Add("fistfuckers");
        EN_English.Add("fistfucking");
        EN_English.Add("fistfuckings");
        EN_English.Add("fistfucks");
        EN_English.Add("flange");
        EN_English.Add("fook");
        EN_English.Add("fooker");
        EN_English.Add("fuck");
        EN_English.Add("fucka");
        EN_English.Add("fucked");
        EN_English.Add("fucker");
        EN_English.Add("fuckers");
        EN_English.Add("fuckhead,fuckheads");
        EN_English.Add("fuckin");
        EN_English.Add("fucking");
        EN_English.Add("fuckings");
        EN_English.Add("fuckingshitmotherfucker");
        EN_English.Add("fuckme");
        EN_English.Add("fucks");
        EN_English.Add("fuckwhit");
        EN_English.Add("fuckwit");
        EN_English.Add("fudge packer");
        EN_English.Add("fudgepacker");
        EN_English.Add("fuk");
        EN_English.Add("fuker");
        EN_English.Add("fukker");
        EN_English.Add("fukkin");
        EN_English.Add("fuks");
        EN_English.Add("fukwhit");
        EN_English.Add("fukwit");
        EN_English.Add("fux");
        EN_English.Add("fux0r");
        EN_English.Add("f_u_c_k");
        EN_English.Add("gangbang");
        EN_English.Add("gangbanged");
        EN_English.Add("gangbangs");
        EN_English.Add("gaylord");
        EN_English.Add("gaysex");
        EN_English.Add("goatse");
        EN_English.Add("god - dam");
        EN_English.Add("god - damned");
        EN_English.Add("goddamn");
        EN_English.Add("goddamned");
        EN_English.Add("hardcoresex");
        EN_English.Add("hell");
        EN_English.Add("heshe");
        EN_English.Add("hoar");
        EN_English.Add("hoare");
        EN_English.Add("hoer");
        EN_English.Add("homo");
        EN_English.Add("hore");
        EN_English.Add("horniest");
        EN_English.Add("horny");
        EN_English.Add("hotsex");
        EN_English.Add("jack - off");
        EN_English.Add("jackoff");
        EN_English.Add("jap");
        EN_English.Add("jerk - off");
        EN_English.Add("jism");
        EN_English.Add("jiz");
        EN_English.Add("jizm");
        EN_English.Add("jizz");
        EN_English.Add("kawk");
        EN_English.Add("knob");
        EN_English.Add("knobead");
        EN_English.Add("knobed");
        EN_English.Add("knobend");
        EN_English.Add("knobhead");
        EN_English.Add("knobjocky");
        EN_English.Add("knobjokey");
        EN_English.Add("kock");
        EN_English.Add("kondum");
        EN_English.Add("kondums");
        EN_English.Add("kum");
        EN_English.Add("kummer");
        EN_English.Add("kumming");
        EN_English.Add("kums");
        EN_English.Add("kunilingus");
        EN_English.Add("l3i + ch");
        EN_English.Add("l3itch");
        EN_English.Add("labia");
        EN_English.Add("lmfao");
        EN_English.Add("lust");
        EN_English.Add("lusting");
        EN_English.Add("m0f0");
        EN_English.Add("m0fo");
        EN_English.Add("m45terbate");
        EN_English.Add("ma5terb8");
        EN_English.Add("ma5terbate");
        EN_English.Add("masochist");
        EN_English.Add("master - bate");
        EN_English.Add("masterb8");
        EN_English.Add("masterbat");
        EN_English.Add("masterbat3");
        EN_English.Add("masterbate");
        EN_English.Add("masterbation");
        EN_English.Add("masterbations");
        EN_English.Add("masturbate");
        EN_English.Add("mo - fo");
        EN_English.Add("mof0");
        EN_English.Add("mofo");
        EN_English.Add("mothafuck");
        EN_English.Add("mothafucka");
        EN_English.Add("mothafuckas");
        EN_English.Add("mothafuckaz");
        EN_English.Add("mothafucked");
        EN_English.Add("mothafucker");
        EN_English.Add("mothafuckers");
        EN_English.Add("mothafuckin");
        EN_English.Add("mothafucking");
        EN_English.Add("mothafuckings");
        EN_English.Add("mothafucks");
        EN_English.Add("mother fucker");
        EN_English.Add("motherfuck");
        EN_English.Add("motherfucked");
        EN_English.Add("motherfucker");
        EN_English.Add("motherfuckers");
        EN_English.Add("motherfuckin");
        EN_English.Add("motherfucking");
        EN_English.Add("motherfuckings");
        EN_English.Add("motherfuckka");
        EN_English.Add("motherfucks");
        EN_English.Add("muff");
        EN_English.Add("mutha");
        EN_English.Add("muthafecker");
        EN_English.Add("muthafuckker");
        EN_English.Add("muther");
        EN_English.Add("mutherfucker");
        EN_English.Add("n1gga");
        EN_English.Add("n1gger");
        EN_English.Add("nazi");
        EN_English.Add("nigg3r");
        EN_English.Add("nigg4h");
        EN_English.Add("nigga");
        EN_English.Add("niggah");
        EN_English.Add("niggas");
        EN_English.Add("niggaz");
        EN_English.Add("nigger");
        EN_English.Add("niggers");
        EN_English.Add("nob");
        EN_English.Add("nob jokey");
        EN_English.Add("nobhead");
        EN_English.Add("nobjocky");
        EN_English.Add("nobjokey");
        EN_English.Add("numbnuts");
        EN_English.Add("nutsack");
        EN_English.Add("orgasim");
        EN_English.Add("orgasims");
        EN_English.Add("orgasm");
        EN_English.Add("orgasms");
        EN_English.Add("p0rn");
        EN_English.Add("pawn");
        EN_English.Add("pecker");
        EN_English.Add("penis");
        EN_English.Add("penisfucker");
        EN_English.Add("phonesex");
        EN_English.Add("phuck");
        EN_English.Add("phuk");
        EN_English.Add("phuked");
        EN_English.Add("phuking");
        EN_English.Add("phukked");
        EN_English.Add("phukking");
        EN_English.Add("phuks");
        EN_English.Add("phuq");
        EN_English.Add("pigfucker");
        EN_English.Add("pimpis");
        EN_English.Add("piss");
        EN_English.Add("pissed");
        EN_English.Add("pisser");
        EN_English.Add("pissers");
        EN_English.Add("pisses");
        EN_English.Add("pissflaps");
        EN_English.Add("pissin");
        EN_English.Add("pissing");
        EN_English.Add("pissoff");
        EN_English.Add("poop");
        EN_English.Add("porn");
        EN_English.Add("porno");
        EN_English.Add("pornography");
        EN_English.Add("pornos");
        EN_English.Add("prick");
        EN_English.Add("pricks");
        EN_English.Add("pron");
        EN_English.Add("pube");
        EN_English.Add("pusse");
        EN_English.Add("pussi");
        EN_English.Add("pussies");
        EN_English.Add("pussy");
        EN_English.Add("pussys");
        EN_English.Add("rectum");
        EN_English.Add("retard");
        EN_English.Add("rimjaw");
        EN_English.Add("rimming");
        EN_English.Add("s hit");
        EN_English.Add("s.o.b.");
        EN_English.Add("sadist");
        EN_English.Add("schlong");
        EN_English.Add("screwing");
        EN_English.Add("scroat");
        EN_English.Add("scrote");
        EN_English.Add("scrotum");
        EN_English.Add("semen");
        EN_English.Add("sex");
        EN_English.Add("sh!+");
        EN_English.Add("sh!t");
        EN_English.Add("sh1t");
        EN_English.Add("shag");
        EN_English.Add("shagger");
        EN_English.Add("shaggin");
        EN_English.Add("shagging");
        EN_English.Add("shemale");
        EN_English.Add("shi +");
        EN_English.Add("shit");
        EN_English.Add("shitdick");
        EN_English.Add("shite");
        EN_English.Add("shited");
        EN_English.Add("shitey");
        EN_English.Add("shitfuck");
        EN_English.Add("shitfull");
        EN_English.Add("shithead");
        EN_English.Add("shiting");
        EN_English.Add("shitings");
        EN_English.Add("shits");
        EN_English.Add("shitted");
        EN_English.Add("shitter");
        EN_English.Add("shitters");
        EN_English.Add("shitting");
        EN_English.Add("shittings");
        EN_English.Add("shitty");
        EN_English.Add("skank");
        EN_English.Add("slut");
        EN_English.Add("sluts");
        EN_English.Add("smegma");
        EN_English.Add("smut");
        EN_English.Add("snatch");
        EN_English.Add("son - of - a - bitch");
        EN_English.Add("spac");
        EN_English.Add("spunk");
        EN_English.Add("s_h_i_t");
        EN_English.Add("t1tt1e5");
        EN_English.Add("t1tties");
        EN_English.Add("teets");
        EN_English.Add("teez");
        EN_English.Add("testical");
        EN_English.Add("testicle");
        EN_English.Add("tit");
        EN_English.Add("titfuck");
        EN_English.Add("tits");
        EN_English.Add("titt");
        EN_English.Add("tittie5");
        EN_English.Add("tittiefucker");
        EN_English.Add("titties");
        EN_English.Add("tittyfuck");
        EN_English.Add("tittywank");
        EN_English.Add("titwank");
        EN_English.Add("tosser");
        EN_English.Add("turd");
        EN_English.Add("tw4t");
        EN_English.Add("twat");
        EN_English.Add("twathead");
        EN_English.Add("twatty");
        EN_English.Add("twunt");
        EN_English.Add("twunter");
        EN_English.Add("v14gra");
        EN_English.Add("v1gra");
        EN_English.Add("vagina");
        EN_English.Add("viagra");
        EN_English.Add("vulva");
        EN_English.Add("w00se");
        EN_English.Add("wang");
        EN_English.Add("wank");
        EN_English.Add("wanker");
        EN_English.Add("wanky");
        EN_English.Add("whoar");
        EN_English.Add("whore");
        EN_English.Add("willies");
        EN_English.Add("willy");
        EN_English.Add("xrated");
        EN_English.Add("xxx");
        EN_English.Add("bollocks");
        EN_English.Add("child - fucker");
        EN_English.Add("Christ on a bike");
        EN_English.Add("Christ on a cracker");
        EN_English.Add("swear word");
        EN_English.Add("godsdamn");
        EN_English.Add("holy shit");
        EN_English.Add("Jesus");
        EN_English.Add("Jesus Christ");
        EN_English.Add("Jesus H.Christ");
        EN_English.Add("Jesus Harold Christ");
        EN_English.Add("Jesus wept");
        EN_English.Add("Jesus, Mary and Joseph");
        EN_English.Add("Judas Priest");
        EN_English.Add("shit ass");
        EN_English.Add("shitass");
        EN_English.Add("son of a bitch");
        EN_English.Add("son of a motherless goat");
        EN_English.Add("son of a whore");
        EN_English.Add("sweet Jesus");
        EN_English.Add("2g1c");
        EN_English.Add("2 girls 1 cup");
        EN_English.Add("acrotomophilia");
        EN_English.Add("alabama hot pocket");
        EN_English.Add("alaskan pipeline");
        EN_English.Add("anilingus");
        EN_English.Add("apeshit");
        EN_English.Add("arsehole");
        EN_English.Add("assmunch");
        EN_English.Add("auto erotic");
        EN_English.Add("autoerotic");
        EN_English.Add("babeland");
        EN_English.Add("baby batter");
        EN_English.Add("baby juice");
        EN_English.Add("ball gag");
        EN_English.Add("ball gravy");
        EN_English.Add("ball kicking");
        EN_English.Add("ball licking");
        EN_English.Add("ball sack");
        EN_English.Add("ball sucking");
        EN_English.Add("bangbros");
        EN_English.Add("bareback");
        EN_English.Add("barely legal");
        EN_English.Add("barenaked");
        EN_English.Add("bastardo");
        EN_English.Add("bastinado");
        EN_English.Add("bbw");
        EN_English.Add("bdsm");
        EN_English.Add("beaner");
        EN_English.Add("beaners");
        EN_English.Add("beaver cleaver");
        EN_English.Add("beaver lips");
        EN_English.Add("big black");
        EN_English.Add("big breasts");
        EN_English.Add("big knockers");
        EN_English.Add("big tits");
        EN_English.Add("bimbos");
        EN_English.Add("birdlock");
        EN_English.Add("black cock");
        EN_English.Add("blonde action");
        EN_English.Add("blonde on blonde action");
        EN_English.Add("blow your load");
        EN_English.Add("blue waffle");
        EN_English.Add("blumpkin");
        EN_English.Add("bondage");
        EN_English.Add("booty call");
        EN_English.Add("brown showers");
        EN_English.Add("brunette action");
        EN_English.Add("bukkake");
        EN_English.Add("bulldyke");
        EN_English.Add("bullet vibe");
        EN_English.Add("bullshit");
        EN_English.Add("bung hole");
        EN_English.Add("bunghole");
        EN_English.Add("busty");
        EN_English.Add("buttcheeks");
        EN_English.Add("camel toe");
        EN_English.Add("camgirl");
        EN_English.Add("camslut");
        EN_English.Add("camwhore");
        EN_English.Add("carpetmuncher");
        EN_English.Add("chocolate rosebuds");
        EN_English.Add("circlejerk");
        EN_English.Add("cleveland steamer");
        EN_English.Add("clover clamps");
        EN_English.Add("clusterfuck");
        EN_English.Add("coprolagnia");
        EN_English.Add("coprophilia");
        EN_English.Add("cornhole");
        EN_English.Add("coons");
        EN_English.Add("creampie");
        EN_English.Add("darkie");
        EN_English.Add("date rape");
        EN_English.Add("daterape");
        EN_English.Add("deep throat");
        EN_English.Add("deepthroat");
        EN_English.Add("dendrophilia");
        EN_English.Add("dingleberry");
        EN_English.Add("dingleberries");
        EN_English.Add("dirty pillows");
        EN_English.Add("dirty sanchez");
        EN_English.Add("doggie style");
        EN_English.Add("doggiestyle");
        EN_English.Add("doggy style");
        EN_English.Add("doggystyle");
        EN_English.Add("dog style");
        EN_English.Add("dolcett");
        EN_English.Add("domination");
        EN_English.Add("dominatrix");
        EN_English.Add("dommes");
        EN_English.Add("donkey punch");
        EN_English.Add("double dong");
        EN_English.Add("double penetration");
        EN_English.Add("dp action");
        EN_English.Add("dry hump");
        EN_English.Add("dvda");
        EN_English.Add("eat my ass");
        EN_English.Add("ecchi");
        EN_English.Add("erotic");
        EN_English.Add("erotism");
        EN_English.Add("escort");
        EN_English.Add("eunuch");
        EN_English.Add("fecal");
        EN_English.Add("felch");
        EN_English.Add("feltch");
        EN_English.Add("female squirting");
        EN_English.Add("femdom");
        EN_English.Add("figging");
        EN_English.Add("fingerbang");
        EN_English.Add("fingering");
        EN_English.Add("fisting");
        EN_English.Add("foot fetish");
        EN_English.Add("footjob");
        EN_English.Add("frotting");
        EN_English.Add("fuck buttons");
        EN_English.Add("fucktards");
        EN_English.Add("futanari");
        EN_English.Add("gang bang");
        EN_English.Add("gay sex");
        EN_English.Add("genitals");
        EN_English.Add("giant cock");
        EN_English.Add("girl on");
        EN_English.Add("girl on top");
        EN_English.Add("girls gone wild");
        EN_English.Add("goatcx");
        EN_English.Add("god damn");
        EN_English.Add("gokkun");
        EN_English.Add("golden shower");
        EN_English.Add("goodpoop");
        EN_English.Add("goo girl");
        EN_English.Add("goregasm");
        EN_English.Add("grope");
        EN_English.Add("group sex");
        EN_English.Add("g - spot");
        EN_English.Add("guro");
        EN_English.Add("hand job");
        EN_English.Add("handjob");
        EN_English.Add("hard core");
        EN_English.Add("hardcore");
        EN_English.Add("hentai");
        EN_English.Add("homoerotic");
        EN_English.Add("honkey");
        EN_English.Add("hooker");
        EN_English.Add("hot carl");
        EN_English.Add("hot chick");
        EN_English.Add("how to kill");
        EN_English.Add("how to murder");
        EN_English.Add("huge fat");
        EN_English.Add("humping");
        EN_English.Add("incest");
        EN_English.Add("intercourse");
        EN_English.Add("jack off");
        EN_English.Add("jail bait");
        EN_English.Add("jailbait");
        EN_English.Add("jelly donut");
        EN_English.Add("jerk off");
        EN_English.Add("jigaboo");
        EN_English.Add("jiggaboo");
        EN_English.Add("jiggerboo");
        EN_English.Add("juggs");
        EN_English.Add("kike");
        EN_English.Add("kinbaku");
        EN_English.Add("kinkster");
        EN_English.Add("kinky");
        EN_English.Add("knobbing");
        EN_English.Add("leather restraint");
        EN_English.Add("leather straight jacket");
        EN_English.Add("lemon party");
        EN_English.Add("lolita");
        EN_English.Add("lovemaking");
        EN_English.Add("make me come");
        EN_English.Add("male squirting");
        EN_English.Add("menage a trois");
        EN_English.Add("milf");
        EN_English.Add("missionary position");
        EN_English.Add("mound of venus");
        EN_English.Add("mr hands");
        EN_English.Add("muff diver");
        EN_English.Add("muffdiving");
        EN_English.Add("nambla");
        EN_English.Add("nawashi");
        EN_English.Add("negro");
        EN_English.Add("neonazi");
        EN_English.Add("nig nog");
        EN_English.Add("nimphomania");
        EN_English.Add("nipple");
        EN_English.Add("nipples");
        EN_English.Add("nsfw images");
        EN_English.Add("nude");
        EN_English.Add("nudity");
        EN_English.Add("nympho");
        EN_English.Add("nymphomania");
        EN_English.Add("octopussy");
        EN_English.Add("omorashi");
        EN_English.Add("one cup two girls");
        EN_English.Add("one guy one jar");
        EN_English.Add("orgy");
        EN_English.Add("paedophile");
        EN_English.Add("paki");
        EN_English.Add("panties");
        EN_English.Add("panty");
        EN_English.Add("pedobear");
        EN_English.Add("pedophile");
        EN_English.Add("pegging");
        EN_English.Add("phone sex");
        EN_English.Add("piece of shit");
        EN_English.Add("piss pig");
        EN_English.Add("pisspig");
        EN_English.Add("playboy");
        EN_English.Add("pleasure chest");
        EN_English.Add("pole smoker");
        EN_English.Add("ponyplay");
        EN_English.Add("poof");
        EN_English.Add("poon");
        EN_English.Add("poontang");
        EN_English.Add("punany");
        EN_English.Add("poop chute");
        EN_English.Add("poopchute");
        EN_English.Add("prince albert piercing");
        EN_English.Add("pthc");
        EN_English.Add("pubes");
        EN_English.Add("queaf");
        EN_English.Add("queef");
        EN_English.Add("quim");
        EN_English.Add("raghead");
        EN_English.Add("raging boner");
        EN_English.Add("rape");
        EN_English.Add("raping");
        EN_English.Add("rapist");
        EN_English.Add("reverse cowgirl");
        EN_English.Add("rimjob");
        EN_English.Add("rosy palm");
        EN_English.Add("rosy palm and her 5 sisters");
        EN_English.Add("rusty trombone");
        EN_English.Add("sadism");
        EN_English.Add("santorum");
        EN_English.Add("scat");
        EN_English.Add("scissoring");
        EN_English.Add("sexo");
        EN_English.Add("sexy");
        EN_English.Add("shaved beaver");
        EN_English.Add("shaved pussy");
        EN_English.Add("shibari");
        EN_English.Add("shitblimp");
        EN_English.Add("shota");
        EN_English.Add("shrimping");
        EN_English.Add("skeet");
        EN_English.Add("slanteye");
        EN_English.Add("s & m");
        EN_English.Add("snowballing");
        EN_English.Add("sodomize");
        EN_English.Add("sodomy");
        EN_English.Add("spic");
        EN_English.Add("splooge");
        EN_English.Add("splooge moose");
        EN_English.Add("spooge");
        EN_English.Add("spread legs");
        EN_English.Add("strap on");
        EN_English.Add("strapon");
        EN_English.Add("strappado");
        EN_English.Add("strip club");
        EN_English.Add("style doggy");
        EN_English.Add("suck");
        EN_English.Add("sucks");
        EN_English.Add("suicide girls");
        EN_English.Add("sultry women");
        EN_English.Add("swastika");
        EN_English.Add("swinger");
        EN_English.Add("tainted love");
        EN_English.Add("taste my");
        EN_English.Add("tea bagging");
        EN_English.Add("threesome");
        EN_English.Add("throating");
        EN_English.Add("tied up");
        EN_English.Add("tight white");
        EN_English.Add("titty");
        EN_English.Add("tongue in a");
        EN_English.Add("topless");
        EN_English.Add("towelhead");
        EN_English.Add("tranny");
        EN_English.Add("tribadism");
        EN_English.Add("tub girl");
        EN_English.Add("tubgirl");
        EN_English.Add("tushy");
        EN_English.Add("twink");
        EN_English.Add("twinkie");
        EN_English.Add("two girls one cup");
        EN_English.Add("undressing");
        EN_English.Add("upskirt");
        EN_English.Add("urethra play");
        EN_English.Add("urophilia");
        EN_English.Add("venus mound");
        EN_English.Add("vibrator");
        EN_English.Add("violet wand");
        EN_English.Add("vorarephilia");
        EN_English.Add("voyeur");
        EN_English.Add("wetback");
        EN_English.Add("wet dream");
        EN_English.Add("white power");
        EN_English.Add("wrapping men");
        EN_English.Add("wrinkled starfish");
        EN_English.Add("xx");
        EN_English.Add("yaoi");
        EN_English.Add("yellow showers");
        EN_English.Add("yiffy");
        EN_English.Add("zoophilia");
        EN_English.Add("a54");
        EN_English.Add("buttmunch");
        EN_English.Add("donkeypunch");
        EN_English.Add("fleshflute");
        EN_English.Add("asswipe");
        EN_English.Add("ho");
        EN_English.Add("bitchass");
        EN_English.Add("moo moo foo foo");
        EN_English.Add("trumped");
        EN_English.Add("assbag");
        EN_English.Add("assbandit");
        EN_English.Add("assbanger");
        EN_English.Add("assbite");
        EN_English.Add("assclown");
        EN_English.Add("asscock");
        EN_English.Add("asscracker");
        EN_English.Add("assface");
        EN_English.Add("assfuck");
        EN_English.Add("assgoblin");
        EN_English.Add("asshat");
        EN_English.Add("ass - hat");
        EN_English.Add("asshead");
        EN_English.Add("asshopper");
        EN_English.Add("ass - jabber");
        EN_English.Add("assjacker");
        EN_English.Add("asslick");
        EN_English.Add("asslicker");
        EN_English.Add("assmonkey");
        EN_English.Add("assmuncher");
        EN_English.Add("assnigger");
        EN_English.Add("asspirate");
        EN_English.Add("ass - pirate");
        EN_English.Add("assshit");
        EN_English.Add("assshole");
        EN_English.Add("asssucker");
        EN_English.Add("asswad");
        EN_English.Add("axwound");
        EN_English.Add("bampot");
        EN_English.Add("bitchtits");
        EN_English.Add("bitchy");
        EN_English.Add("bollox");
        EN_English.Add("brotherfucker");
        EN_English.Add("bumblefuck");
        EN_English.Add("butt plug");
        EN_English.Add("buttfucka");
        EN_English.Add("butt - pirate");
        EN_English.Add("buttfucker");
        EN_English.Add("chesticle");
        EN_English.Add("chinc");
        EN_English.Add("choad");
        EN_English.Add("chode");
        EN_English.Add("clitface");
        EN_English.Add("clitfuck");
        EN_English.Add("cockass");
        EN_English.Add("cockbite");
        EN_English.Add("cockburger");
        EN_English.Add("cockfucker");
        EN_English.Add("cockjockey");
        EN_English.Add("cockknoker");
        EN_English.Add("cockmaster");
        EN_English.Add("cockmongler");
        EN_English.Add("cockmongruel");
        EN_English.Add("cockmonkey");
        EN_English.Add("cocknose");
        EN_English.Add("cocknugget");
        EN_English.Add("cockshit");
        EN_English.Add("cocksmith");
        EN_English.Add("cocksmoke");
        EN_English.Add("cocksmoker");
        EN_English.Add("cocksniffer");
        EN_English.Add("cockwaffle");
        EN_English.Add("coochie");
        EN_English.Add("coochy");
        EN_English.Add("cooter");
        EN_English.Add("cracker");
        EN_English.Add("cumbubble");
        EN_English.Add("cumdumpster");
        EN_English.Add("cumguzzler");
        EN_English.Add("cumjockey");
        EN_English.Add("cumslut");
        EN_English.Add("cumtart");
        EN_English.Add("cunnie");
        EN_English.Add("cuntass");
        EN_English.Add("cuntface");
        EN_English.Add("cunthole");
        EN_English.Add("cuntrag");
        EN_English.Add("cuntslut");
        EN_English.Add("dago");
        EN_English.Add("deggo");
        EN_English.Add("dickbag");
        EN_English.Add("dickbeaters");
        EN_English.Add("dickface");
        EN_English.Add("dickfuck");
        EN_English.Add("dickfucker");
        EN_English.Add("dickhole");
        EN_English.Add("dickjuice");
        EN_English.Add("dickmilk");
        EN_English.Add("dickmonger");
        EN_English.Add("dicks");
        EN_English.Add("dickslap");
        EN_English.Add("dick - sneeze");
        EN_English.Add("dicksucker");
        EN_English.Add("dicksucking");
        EN_English.Add("dicktickler");
        EN_English.Add("dickwad");
        EN_English.Add("dickweasel");
        EN_English.Add("dickweed");
        EN_English.Add("dickwod");
        EN_English.Add("dike");
        EN_English.Add("dipshit");
        EN_English.Add("doochbag");
        EN_English.Add("dookie");
        EN_English.Add("douche");
        EN_English.Add("douchebag");
        EN_English.Add("douche - fag");
        EN_English.Add("douchewaffle");
        EN_English.Add("dumass");
        EN_English.Add("dumb ass");
        EN_English.Add("dumbass");
        EN_English.Add("dumbfuck");
        EN_English.Add("dumbshit");
        EN_English.Add("dumshit");
        EN_English.Add("fagbag");
        EN_English.Add("fagfucker");
        EN_English.Add("faggit");
        EN_English.Add("faggotcock");
        EN_English.Add("fagtard");
        EN_English.Add("flamer");
        EN_English.Add("fuckass");
        EN_English.Add("fuckbag");
        EN_English.Add("fuckboy");
        EN_English.Add("fuckbrain");
        EN_English.Add("fuckbutt");
        EN_English.Add("fuckbutter");
        EN_English.Add("fuckersucker");
        EN_English.Add("fuckface");
        EN_English.Add("fuckhole");
        EN_English.Add("fucknut");
        EN_English.Add("fucknutt");
        EN_English.Add("fuckoff");
        EN_English.Add("fuckstick");
        EN_English.Add("fucktard");
        EN_English.Add("fucktart");
        EN_English.Add("fuckup");
        EN_English.Add("fuckwad");
        EN_English.Add("fuckwitt");
        EN_English.Add("gay");
        EN_English.Add("gayass");
        EN_English.Add("gaybob");
        EN_English.Add("gaydo");
        EN_English.Add("gayfuck");
        EN_English.Add("gayfuckist");
        EN_English.Add("gaytard");
        EN_English.Add("gaywad");
        EN_English.Add("goddamnit");
        EN_English.Add("gooch");
        EN_English.Add("gook");
        EN_English.Add("gringo");
        EN_English.Add("guido");
        EN_English.Add("hard on");
        EN_English.Add("heeb");
        EN_English.Add("hoe");
        EN_English.Add("homodumbshit");
        EN_English.Add("jackass");
        EN_English.Add("jagoff");
        EN_English.Add("jerkass");
        EN_English.Add("jungle bunny");
        EN_English.Add("junglebunny");
        EN_English.Add("kooch");
        EN_English.Add("kootch");
        EN_English.Add("kraut");
        EN_English.Add("kunt");
        EN_English.Add("kyke");
        EN_English.Add("lameass");
        EN_English.Add("lardass");
        EN_English.Add("lesbian");
        EN_English.Add("lesbo");
        EN_English.Add("lezzie");
        EN_English.Add("mcfagget");
        EN_English.Add("mick");
        EN_English.Add("minge");
        EN_English.Add("muffdiver");
        EN_English.Add("munging");
        EN_English.Add("nigaboo");
        EN_English.Add("niglet");
        EN_English.Add("nut sack");
        EN_English.Add("panooch");
        EN_English.Add("peckerhead");
        EN_English.Add("penisbanger");
        EN_English.Add("penispuffer");
        EN_English.Add("pissed off");
        EN_English.Add("polesmoker");
        EN_English.Add("pollock");
        EN_English.Add("poonani");
        EN_English.Add("poonany");
        EN_English.Add("porch monkey");
        EN_English.Add("porchmonkey");
        EN_English.Add("punanny");
        EN_English.Add("punta");
        EN_English.Add("pussylicking");
        EN_English.Add("puto");
        EN_English.Add("queer");
        EN_English.Add("queerbait");
        EN_English.Add("queerhole");
        EN_English.Add("renob");
        EN_English.Add("ruski");
        EN_English.Add("sand nigger");
        EN_English.Add("sandnigger");
        EN_English.Add("shitbag");
        EN_English.Add("shitbagger");
        EN_English.Add("shitbrains");
        EN_English.Add("shitbreath");
        EN_English.Add("shitcanned");
        EN_English.Add("shitcunt");
        EN_English.Add("shitface");
        EN_English.Add("shitfaced");
        EN_English.Add("shithole");
        EN_English.Add("shithouse");
        EN_English.Add("shitspitter");
        EN_English.Add("shitstain");
        EN_English.Add("shittiest");
        EN_English.Add("shiz");
        EN_English.Add("shiznit");
        EN_English.Add("skullfuck");
        EN_English.Add("slutbag");
        EN_English.Add("smeg");
        EN_English.Add("spick");
        EN_English.Add("spook");
        EN_English.Add("suckass");
        EN_English.Add("tard");
        EN_English.Add("thundercunt");
        EN_English.Add("twatlips");
        EN_English.Add("twats");
        EN_English.Add("twatwaffle");
        EN_English.Add("unclefucker");
        EN_English.Add("vag");
        EN_English.Add("vajayjay");
        EN_English.Add("va - j - j");
        EN_English.Add("vjayjay");
        EN_English.Add("wankjob");
        EN_English.Add("whorebag");
        EN_English.Add("whoreface");
        EN_English.Add("wop");
        EN_English.Add("fuck you");
        EN_English.Add("piss off");
        EN_English.Add("dick head");
        EN_English.Add("bloody hell");
        EN_English.Add("crikey");
        EN_English.Add("rubbish");
        EN_English.Add("taking the piss");
        EN_English.Add("jerk");
        EN_English.Add("knob end");
        EN_English.Add("lmao");
        EN_English.Add("omg");
        EN_English.Add("wtf");
        EN_English.Add("bint");
        EN_English.Add("ginger");
        EN_English.Add("git");
        EN_English.Add("minger");
        EN_English.Add("munter");
        EN_English.Add("sod off");
        EN_English.Add("chinky");
        EN_English.Add("choc ice");
        EN_English.Add("gippo");
        EN_English.Add("golliwog");
        EN_English.Add("hun");
        EN_English.Add("iap");
        EN_English.Add("jock");
        EN_English.Add("nig - nog");
        EN_English.Add("pikey");
        EN_English.Add("polack");
        EN_English.Add("sambo");
        EN_English.Add("slope");
        EN_English.Add("spade");
        EN_English.Add("taff");
        EN_English.Add("wog");
        EN_English.Add("beaver");
        EN_English.Add("beef curtains");
        EN_English.Add("bloodclaat");
        EN_English.Add("clunge");
        EN_English.Add("flaps");
        EN_English.Add("gash");
        EN_English.Add("punani");
        EN_English.Add("batty boy");
        EN_English.Add("bender");
        EN_English.Add("bum boy");
        EN_English.Add("bumclat");
        EN_English.Add("bummer");
        EN_English.Add("chi - chi man");
        EN_English.Add("chick with a dick");
        EN_English.Add("fudge - packer");
        EN_English.Add("gender bender");
        EN_English.Add("he - she");
        EN_English.Add("lezza / lesbo");
        EN_English.Add("pansy");
        EN_English.Add("shirt lifter");
        EN_English.Add("cretin");
        EN_English.Add("cripple");
        EN_English.Add("div");
        EN_English.Add("looney");
        EN_English.Add("midget");
        EN_English.Add("mong");
        EN_English.Add("nutter");
        EN_English.Add("psycho");
        EN_English.Add("schizo");
        EN_English.Add("veqtable");
        EN_English.Add("window licker");
        EN_English.Add("fenian");
        EN_English.Add("kafir");
        EN_English.Add("prod");
        EN_English.Add("taig");
        EN_English.Add("yid");
        EN_English.Add("iberian slap");
        EN_English.Add("middle finger");
        EN_English.Add("two fingers with tongue");
        EN_English.Add("two fingers");
        EN_English.Add("nonce");
        EN_English.Add("prickteaser");
        EN_English.Add("rapey");
        EN_English.Add("slag");
        EN_English.Add("tart");
        EN_English.Add("coffin dodger");
        EN_English.Add("old bag");
        EN_English.Add("frenchify");
        EN_English.Add("bescumber");
        EN_English.Add("microphallus");
        EN_English.Add("coccydynia");
        EN_English.Add("ninnyhammer");
        EN_English.Add("buncombe");
        EN_English.Add("hircismus");
        EN_English.Add("corpulent");
        EN_English.Add("feist");
        EN_English.Add("fice");
        EN_English.Add("cacafuego");
        EN_English.Add("ass fuck");
        EN_English.Add("assfaces");
        EN_English.Add("assmucus");
        EN_English.Add("bang(one's) box   ");
        EN_English.Add("bastards");
        EN_English.Add("beef curtain");
        EN_English.Add("bitch tit");
        EN_English.Add("blow me");
        EN_English.Add("blow mud");
        EN_English.Add("blue waffle");
        EN_English.Add("blumpkin");
        EN_English.Add("bust a load");
        EN_English.Add("butt fuck");
        EN_English.Add("choade");
        EN_English.Add("chota bags");
        EN_English.Add("clit licker");
        EN_English.Add("clitty litter");
        EN_English.Add("cock pocket");
        EN_English.Add("cock snot");
        EN_English.Add("cocksuck");
        EN_English.Add("cocksucked");
        EN_English.Add("cocksuckers");
        EN_English.Add("cocksucks");
        EN_English.Add("cop some wood");
        EN_English.Add("cornhole");
        EN_English.Add("corp whore");
        EN_English.Add("cum chugger");
        EN_English.Add("cum dumpster");
        EN_English.Add("cum freak");
        EN_English.Add("cum guzzler");
        EN_English.Add("cumdump");
        EN_English.Add("cunt hair");
        EN_English.Add("cuntbag");
        EN_English.Add("cuntlick");
        EN_English.Add("cuntlicker");
        EN_English.Add("cuntlicking");
        EN_English.Add("cuntsicle");
        EN_English.Add("cunt - struck");
        EN_English.Add("cut rope");
        EN_English.Add("cyberfuck");
        EN_English.Add("cyberfucked");
        EN_English.Add("cyberfucking");
        EN_English.Add("dick hole");
        EN_English.Add("dick shy");
        EN_English.Add("dickheads");
        EN_English.Add("dirty Sanchez");
        EN_English.Add("eat a dick");
        EN_English.Add("eat hair pie");
        EN_English.Add("ejaculates");
        EN_English.Add("ejaculating");
        EN_English.Add("facial");
        EN_English.Add("faggots");
        EN_English.Add("fingerfuck");
        EN_English.Add("fingerfucked");
        EN_English.Add("fingerfucker");
        EN_English.Add("fingerfucking");
        EN_English.Add("fingerfucks");
        EN_English.Add("fist fuck");
        EN_English.Add("fistfucked");
        EN_English.Add("fistfucker");
        EN_English.Add("fistfuckers");
        EN_English.Add("fistfucking");
        EN_English.Add("fistfuckings");
        EN_English.Add("fistfucks");
        EN_English.Add("flog the log");
        EN_English.Add("fuc");
        EN_English.Add("fuck hole");
        EN_English.Add("fuck puppet");
        EN_English.Add("fuck trophy");
        EN_English.Add("fuck yo mama");
        EN_English.Add("fuck");
        EN_English.Add("fuck - ass");
        EN_English.Add("fuck - bitch");
        EN_English.Add("fuckedup");
        EN_English.Add("fuckme");
        EN_English.Add("fuckmeat");
        EN_English.Add("fucktoy");
        EN_English.Add("fukkers");
        EN_English.Add("fuq");
        EN_English.Add("gang - bang");
        EN_English.Add("gassy ass");
        EN_English.Add("god");
        EN_English.Add("ham flap");
        EN_English.Add("how to murdep");
        EN_English.Add("jackasses");
        EN_English.Add("jiz");
        EN_English.Add("jizm");
        EN_English.Add("kinky Jesus");
        EN_English.Add("kwif");
        EN_English.Add("LEN");
        EN_English.Add("mafugly");
        EN_English.Add("mothafucked");
        EN_English.Add("mothafucking");
        EN_English.Add("mother fucker");
        EN_English.Add("muff puff");
        EN_English.Add("need the dick");
        EN_English.Add("nut butter");
        EN_English.Add("pisses");
        EN_English.Add("pissin");
        EN_English.Add("pissoff");
        EN_English.Add("pussy fart");
        EN_English.Add("pussy palace");
        EN_English.Add("queaf");
        EN_English.Add("sandbar");
        EN_English.Add("sausage queen");
        EN_English.Add("shit fucker");
        EN_English.Add("shitheads");
        EN_English.Add("shitters");
        EN_English.Add("shittier");
        EN_English.Add("slope");
        EN_English.Add("slut bucket");
        EN_English.Add("smartass");
        EN_English.Add("smartasses");
        EN_English.Add("tit wank");
        EN_English.Add("tities");
        EN_English.Add("wiseass");
        EN_English.Add("wiseasses");
        EN_English.Add("boong");
        EN_English.Add("coonnass");
        EN_English.Add("darn");
        EN_English.Add("Breeder");
        EN_English.Add("Cocklump");
        EN_English.Add("Doublelift");
        EN_English.Add("Dumbcunt");
        EN_English.Add("Fuck off");
        EN_English.Add("Poopuncher");
        EN_English.Add("Sandler");
        EN_English.Add("cockeye");
        EN_English.Add("crotte");
        EN_English.Add("cus");
        EN_English.Add("foah");
        EN_English.Add("fucktwat");
        EN_English.Add("jaggi");
        EN_English.Add("kunja");
        EN_English.Add("pust");
        EN_English.Add("sanger");
        EN_English.Add("seks");
        EN_English.Add("zubb");
        EN_English.Add("zibbi");

    }
    public void DaWords()
    {

        DA_DK.Add("pik");
        DA_DK.Add("p1k");
        DA_DK.Add("pikhovede");
        DA_DK.Add("pikslikker");
        DA_DK.Add("pikfjæs");
        DA_DK.Add("røv");
        DA_DK.Add("røvhul");
        DA_DK.Add("p1kh0v3d3");
        DA_DK.Add("luder");
        DA_DK.Add("lud3r");
        DA_DK.Add("so");
        DA_DK.Add("s0");
        DA_DK.Add("5m4750");
        DA_DK.Add("kælling");
        DA_DK.Add("kæll1ng");
        DA_DK.Add("kæll1n6");
        DA_DK.Add("røvslikker");
        DA_DK.Add("røvfjæs");
        DA_DK.Add("piksutter");
        DA_DK.Add("Sædsluger");
        DA_DK.Add("pikansjos");
        DA_DK.Add("jesus");
        DA_DK.Add("allah");
        DA_DK.Add("budda");
        DA_DK.Add("satan");
        DA_DK.Add("Perker");
        DA_DK.Add("p3rk3r");
        DA_DK.Add("perk3r");
        DA_DK.Add("P3rker");
        DA_DK.Add("P 3 r k e r");
        DA_DK.Add("P e r k 3 r");
        DA_DK.Add("P 3 r k 3 r");
        DA_DK.Add("P e r k e r");
        DA_DK.Add("Neger");
        DA_DK.Add("n3g3r");
        DA_DK.Add("neg3r");
        DA_DK.Add("n3ger");
        DA_DK.Add("fisse");
        DA_DK.Add("fiss3");
        DA_DK.Add("noob");
        DA_DK.Add("n00b");
        DA_DK.Add("f1553");
        DA_DK.Add("nederen");
        DA_DK.Add("lort");
        DA_DK.Add("l0r7");
        DA_DK.Add("l o r t");



    }
}
